// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Edg.proto
package sa.iff.minatentlocator.ProtoBufUtil;

public final class EdgProto {
  private EdgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EdgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Edg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .Edg.Vtx source = 1;</code>
     */
    boolean hasSource();
    /**
     * <code>required .Edg.Vtx source = 1;</code>
     */
    EdgProto.Edg.Vtx getSource();
    /**
     * <code>required .Edg.Vtx source = 1;</code>
     */
    EdgProto.Edg.VtxOrBuilder getSourceOrBuilder();

    /**
     * <code>required .Edg.Vtx destination = 2;</code>
     */
    boolean hasDestination();
    /**
     * <code>required .Edg.Vtx destination = 2;</code>
     */
    EdgProto.Edg.Vtx getDestination();
    /**
     * <code>required .Edg.Vtx destination = 2;</code>
     */
    EdgProto.Edg.VtxOrBuilder getDestinationOrBuilder();

    /**
     * <code>required double distance = 3;</code>
     */
    boolean hasDistance();
    /**
     * <code>required double distance = 3;</code>
     */
    double getDistance();
  }
  /**
   * Protobuf type {@code Edg}
   */
  public static final class Edg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Edg)
      EdgOrBuilder {
    // Use Edg.newBuilder() to construct.
    private Edg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Edg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Edg defaultInstance;
    public static Edg getDefaultInstance() {
      return defaultInstance;
    }

    public Edg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Edg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              EdgProto.Edg.Vtx.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = source_.toBuilder();
              }
              source_ = input.readMessage(EdgProto.Edg.Vtx.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(source_);
                source_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              EdgProto.Edg.Vtx.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = destination_.toBuilder();
              }
              destination_ = input.readMessage(EdgProto.Edg.Vtx.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(destination_);
                destination_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              distance_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EdgProto.internal_static_Edg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EdgProto.internal_static_Edg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EdgProto.Edg.class, EdgProto.Edg.Builder.class);
    }

    public static com.google.protobuf.Parser<Edg> PARSER =
        new com.google.protobuf.AbstractParser<Edg>() {
      public Edg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Edg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Edg> getParserForType() {
      return PARSER;
    }

    public interface VtxOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Edg.Vtx)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required double Lat = 1;</code>
       */
      boolean hasLat();
      /**
       * <code>required double Lat = 1;</code>
       */
      double getLat();

      /**
       * <code>required double Lng = 2;</code>
       */
      boolean hasLng();
      /**
       * <code>required double Lng = 2;</code>
       */
      double getLng();
    }
    /**
     * Protobuf type {@code Edg.Vtx}
     */
    public static final class Vtx extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Edg.Vtx)
        VtxOrBuilder {
      // Use Vtx.newBuilder() to construct.
      private Vtx(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Vtx(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Vtx defaultInstance;
      public static Vtx getDefaultInstance() {
        return defaultInstance;
      }

      public Vtx getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Vtx(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 9: {
                bitField0_ |= 0x00000001;
                lat_ = input.readDouble();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                lng_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EdgProto.internal_static_Edg_Vtx_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EdgProto.internal_static_Edg_Vtx_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EdgProto.Edg.Vtx.class, EdgProto.Edg.Vtx.Builder.class);
      }

      public static com.google.protobuf.Parser<Vtx> PARSER =
          new com.google.protobuf.AbstractParser<Vtx>() {
        public Vtx parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Vtx(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Vtx> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int LAT_FIELD_NUMBER = 1;
      private double lat_;
      /**
       * <code>required double Lat = 1;</code>
       */
      public boolean hasLat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double Lat = 1;</code>
       */
      public double getLat() {
        return lat_;
      }

      public static final int LNG_FIELD_NUMBER = 2;
      private double lng_;
      /**
       * <code>required double Lng = 2;</code>
       */
      public boolean hasLng() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double Lng = 2;</code>
       */
      public double getLng() {
        return lng_;
      }

      private void initFields() {
        lat_ = 0D;
        lng_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasLat()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLng()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeDouble(1, lat_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, lng_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, lat_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, lng_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static EdgProto.Edg.Vtx parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static EdgProto.Edg.Vtx parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static EdgProto.Edg.Vtx parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static EdgProto.Edg.Vtx parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static EdgProto.Edg.Vtx parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static EdgProto.Edg.Vtx parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static EdgProto.Edg.Vtx parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static EdgProto.Edg.Vtx parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static EdgProto.Edg.Vtx parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static EdgProto.Edg.Vtx parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(EdgProto.Edg.Vtx prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Edg.Vtx}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Edg.Vtx)
          EdgProto.Edg.VtxOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return EdgProto.internal_static_Edg_Vtx_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return EdgProto.internal_static_Edg_Vtx_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  EdgProto.Edg.Vtx.class, EdgProto.Edg.Vtx.Builder.class);
        }

        // Construct using EdgProto.Edg.Vtx.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          lat_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000001);
          lng_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return EdgProto.internal_static_Edg_Vtx_descriptor;
        }

        public EdgProto.Edg.Vtx getDefaultInstanceForType() {
          return EdgProto.Edg.Vtx.getDefaultInstance();
        }

        public EdgProto.Edg.Vtx build() {
          EdgProto.Edg.Vtx result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public EdgProto.Edg.Vtx buildPartial() {
          EdgProto.Edg.Vtx result = new EdgProto.Edg.Vtx(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.lat_ = lat_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.lng_ = lng_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof EdgProto.Edg.Vtx) {
            return mergeFrom((EdgProto.Edg.Vtx)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(EdgProto.Edg.Vtx other) {
          if (other == EdgProto.Edg.Vtx.getDefaultInstance()) return this;
          if (other.hasLat()) {
            setLat(other.getLat());
          }
          if (other.hasLng()) {
            setLng(other.getLng());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasLat()) {
            
            return false;
          }
          return hasLng();
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          EdgProto.Edg.Vtx parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (EdgProto.Edg.Vtx) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private double lat_ ;
        /**
         * <code>required double Lat = 1;</code>
         */
        public boolean hasLat() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required double Lat = 1;</code>
         */
        public double getLat() {
          return lat_;
        }
        /**
         * <code>required double Lat = 1;</code>
         */
        public Builder setLat(double value) {
          bitField0_ |= 0x00000001;
          lat_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double Lat = 1;</code>
         */
        public Builder clearLat() {
          bitField0_ = (bitField0_ & ~0x00000001);
          lat_ = 0D;
          onChanged();
          return this;
        }

        private double lng_ ;
        /**
         * <code>required double Lng = 2;</code>
         */
        public boolean hasLng() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required double Lng = 2;</code>
         */
        public double getLng() {
          return lng_;
        }
        /**
         * <code>required double Lng = 2;</code>
         */
        public Builder setLng(double value) {
          bitField0_ |= 0x00000002;
          lng_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double Lng = 2;</code>
         */
        public Builder clearLng() {
          bitField0_ = (bitField0_ & ~0x00000002);
          lng_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Edg.Vtx)
      }

      static {
        defaultInstance = new Vtx(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Edg.Vtx)
    }

    private int bitField0_;
    public static final int SOURCE_FIELD_NUMBER = 1;
    private EdgProto.Edg.Vtx source_;
    /**
     * <code>required .Edg.Vtx source = 1;</code>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Edg.Vtx source = 1;</code>
     */
    public EdgProto.Edg.Vtx getSource() {
      return source_;
    }
    /**
     * <code>required .Edg.Vtx source = 1;</code>
     */
    public EdgProto.Edg.VtxOrBuilder getSourceOrBuilder() {
      return source_;
    }

    public static final int DESTINATION_FIELD_NUMBER = 2;
    private EdgProto.Edg.Vtx destination_;
    /**
     * <code>required .Edg.Vtx destination = 2;</code>
     */
    public boolean hasDestination() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Edg.Vtx destination = 2;</code>
     */
    public EdgProto.Edg.Vtx getDestination() {
      return destination_;
    }
    /**
     * <code>required .Edg.Vtx destination = 2;</code>
     */
    public EdgProto.Edg.VtxOrBuilder getDestinationOrBuilder() {
      return destination_;
    }

    public static final int DISTANCE_FIELD_NUMBER = 3;
    private double distance_;
    /**
     * <code>required double distance = 3;</code>
     */
    public boolean hasDistance() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double distance = 3;</code>
     */
    public double getDistance() {
      return distance_;
    }

    private void initFields() {
      source_ = EdgProto.Edg.Vtx.getDefaultInstance();
      destination_ = EdgProto.Edg.Vtx.getDefaultInstance();
      distance_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDestination()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDistance()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSource().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getDestination().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, source_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, destination_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, distance_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, source_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, destination_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, distance_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static EdgProto.Edg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EdgProto.Edg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EdgProto.Edg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EdgProto.Edg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EdgProto.Edg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EdgProto.Edg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static EdgProto.Edg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static EdgProto.Edg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static EdgProto.Edg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EdgProto.Edg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(EdgProto.Edg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Edg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Edg)
        EdgProto.EdgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EdgProto.internal_static_Edg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EdgProto.internal_static_Edg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EdgProto.Edg.class, EdgProto.Edg.Builder.class);
      }

      // Construct using EdgProto.Edg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSourceFieldBuilder();
          getDestinationFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (sourceBuilder_ == null) {
          source_ = EdgProto.Edg.Vtx.getDefaultInstance();
        } else {
          sourceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (destinationBuilder_ == null) {
          destination_ = EdgProto.Edg.Vtx.getDefaultInstance();
        } else {
          destinationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        distance_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EdgProto.internal_static_Edg_descriptor;
      }

      public EdgProto.Edg getDefaultInstanceForType() {
        return EdgProto.Edg.getDefaultInstance();
      }

      public EdgProto.Edg build() {
        EdgProto.Edg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public EdgProto.Edg buildPartial() {
        EdgProto.Edg result = new EdgProto.Edg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (sourceBuilder_ == null) {
          result.source_ = source_;
        } else {
          result.source_ = sourceBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (destinationBuilder_ == null) {
          result.destination_ = destination_;
        } else {
          result.destination_ = destinationBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.distance_ = distance_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EdgProto.Edg) {
          return mergeFrom((EdgProto.Edg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EdgProto.Edg other) {
        if (other == EdgProto.Edg.getDefaultInstance()) return this;
        if (other.hasSource()) {
          mergeSource(other.getSource());
        }
        if (other.hasDestination()) {
          mergeDestination(other.getDestination());
        }
        if (other.hasDistance()) {
          setDistance(other.getDistance());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSource()) {
          
          return false;
        }
        if (!hasDestination()) {
          
          return false;
        }
        if (!hasDistance()) {
          
          return false;
        }
        if (!getSource().isInitialized()) {
          
          return false;
        }
        return getDestination().isInitialized();
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EdgProto.Edg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EdgProto.Edg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private EdgProto.Edg.Vtx source_ = EdgProto.Edg.Vtx.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          EdgProto.Edg.Vtx, EdgProto.Edg.Vtx.Builder, EdgProto.Edg.VtxOrBuilder> sourceBuilder_;
      /**
       * <code>required .Edg.Vtx source = 1;</code>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Edg.Vtx source = 1;</code>
       */
      public EdgProto.Edg.Vtx getSource() {
        if (sourceBuilder_ == null) {
          return source_;
        } else {
          return sourceBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Edg.Vtx source = 1;</code>
       */
      public Builder setSource(EdgProto.Edg.Vtx value) {
        if (sourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          source_ = value;
          onChanged();
        } else {
          sourceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Edg.Vtx source = 1;</code>
       */
      public Builder setSource(
          EdgProto.Edg.Vtx.Builder builderForValue) {
        if (sourceBuilder_ == null) {
          source_ = builderForValue.build();
          onChanged();
        } else {
          sourceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Edg.Vtx source = 1;</code>
       */
      public Builder mergeSource(EdgProto.Edg.Vtx value) {
        if (sourceBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              source_ != EdgProto.Edg.Vtx.getDefaultInstance()) {
            source_ =
              EdgProto.Edg.Vtx.newBuilder(source_).mergeFrom(value).buildPartial();
          } else {
            source_ = value;
          }
          onChanged();
        } else {
          sourceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Edg.Vtx source = 1;</code>
       */
      public Builder clearSource() {
        if (sourceBuilder_ == null) {
          source_ = EdgProto.Edg.Vtx.getDefaultInstance();
          onChanged();
        } else {
          sourceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .Edg.Vtx source = 1;</code>
       */
      public EdgProto.Edg.Vtx.Builder getSourceBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSourceFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Edg.Vtx source = 1;</code>
       */
      public EdgProto.Edg.VtxOrBuilder getSourceOrBuilder() {
        if (sourceBuilder_ != null) {
          return sourceBuilder_.getMessageOrBuilder();
        } else {
          return source_;
        }
      }
      /**
       * <code>required .Edg.Vtx source = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          EdgProto.Edg.Vtx, EdgProto.Edg.Vtx.Builder, EdgProto.Edg.VtxOrBuilder> 
          getSourceFieldBuilder() {
        if (sourceBuilder_ == null) {
          sourceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              EdgProto.Edg.Vtx, EdgProto.Edg.Vtx.Builder, EdgProto.Edg.VtxOrBuilder>(
                  getSource(),
                  getParentForChildren(),
                  isClean());
          source_ = null;
        }
        return sourceBuilder_;
      }

      private EdgProto.Edg.Vtx destination_ = EdgProto.Edg.Vtx.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          EdgProto.Edg.Vtx, EdgProto.Edg.Vtx.Builder, EdgProto.Edg.VtxOrBuilder> destinationBuilder_;
      /**
       * <code>required .Edg.Vtx destination = 2;</code>
       */
      public boolean hasDestination() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Edg.Vtx destination = 2;</code>
       */
      public EdgProto.Edg.Vtx getDestination() {
        if (destinationBuilder_ == null) {
          return destination_;
        } else {
          return destinationBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Edg.Vtx destination = 2;</code>
       */
      public Builder setDestination(EdgProto.Edg.Vtx value) {
        if (destinationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          destination_ = value;
          onChanged();
        } else {
          destinationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Edg.Vtx destination = 2;</code>
       */
      public Builder setDestination(
          EdgProto.Edg.Vtx.Builder builderForValue) {
        if (destinationBuilder_ == null) {
          destination_ = builderForValue.build();
          onChanged();
        } else {
          destinationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Edg.Vtx destination = 2;</code>
       */
      public Builder mergeDestination(EdgProto.Edg.Vtx value) {
        if (destinationBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              destination_ != EdgProto.Edg.Vtx.getDefaultInstance()) {
            destination_ =
              EdgProto.Edg.Vtx.newBuilder(destination_).mergeFrom(value).buildPartial();
          } else {
            destination_ = value;
          }
          onChanged();
        } else {
          destinationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Edg.Vtx destination = 2;</code>
       */
      public Builder clearDestination() {
        if (destinationBuilder_ == null) {
          destination_ = EdgProto.Edg.Vtx.getDefaultInstance();
          onChanged();
        } else {
          destinationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .Edg.Vtx destination = 2;</code>
       */
      public EdgProto.Edg.Vtx.Builder getDestinationBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDestinationFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Edg.Vtx destination = 2;</code>
       */
      public EdgProto.Edg.VtxOrBuilder getDestinationOrBuilder() {
        if (destinationBuilder_ != null) {
          return destinationBuilder_.getMessageOrBuilder();
        } else {
          return destination_;
        }
      }
      /**
       * <code>required .Edg.Vtx destination = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          EdgProto.Edg.Vtx, EdgProto.Edg.Vtx.Builder, EdgProto.Edg.VtxOrBuilder> 
          getDestinationFieldBuilder() {
        if (destinationBuilder_ == null) {
          destinationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              EdgProto.Edg.Vtx, EdgProto.Edg.Vtx.Builder, EdgProto.Edg.VtxOrBuilder>(
                  getDestination(),
                  getParentForChildren(),
                  isClean());
          destination_ = null;
        }
        return destinationBuilder_;
      }

      private double distance_ ;
      /**
       * <code>required double distance = 3;</code>
       */
      public boolean hasDistance() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double distance = 3;</code>
       */
      public double getDistance() {
        return distance_;
      }
      /**
       * <code>required double distance = 3;</code>
       */
      public Builder setDistance(double value) {
        bitField0_ |= 0x00000004;
        distance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double distance = 3;</code>
       */
      public Builder clearDistance() {
        bitField0_ = (bitField0_ & ~0x00000004);
        distance_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Edg)
    }

    static {
      defaultInstance = new Edg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Edg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Edg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Edg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Edg_Vtx_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Edg_Vtx_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tEdg.proto\"q\n\003Edg\022\030\n\006source\030\001 \002(\0132\010.Edg" +
      ".Vtx\022\035\n\013destination\030\002 \002(\0132\010.Edg.Vtx\022\020\n\010d" +
      "istance\030\003 \002(\001\032\037\n\003Vtx\022\013\n\003Lat\030\001 \002(\001\022\013\n\003Lng" +
      "\030\002 \002(\001B\nB\010EdgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Edg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Edg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Edg_descriptor,
        new java.lang.String[] { "Source", "Destination", "Distance", });
    internal_static_Edg_Vtx_descriptor =
      internal_static_Edg_descriptor.getNestedTypes().get(0);
    internal_static_Edg_Vtx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Edg_Vtx_descriptor,
        new java.lang.String[] { "Lat", "Lng", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
