// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Vtx.proto
package sa.iff.minatentlocator.ProtoBufUtil;

public final class VtxProto {
  private VtxProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VtxOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Vtx)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double Lat = 1;</code>
     */
    boolean hasLat();
    /**
     * <code>required double Lat = 1;</code>
     */
    double getLat();

    /**
     * <code>required double Lng = 2;</code>
     */
    boolean hasLng();
    /**
     * <code>required double Lng = 2;</code>
     */
    double getLng();
  }
  /**
   * Protobuf type {@code Vtx}
   */
  public static final class Vtx extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Vtx)
      VtxOrBuilder {
    // Use Vtx.newBuilder() to construct.
    private Vtx(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Vtx(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Vtx defaultInstance;
    public static Vtx getDefaultInstance() {
      return defaultInstance;
    }

    public Vtx getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Vtx(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              lat_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              lng_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VtxProto.internal_static_Vtx_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VtxProto.internal_static_Vtx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VtxProto.Vtx.class, VtxProto.Vtx.Builder.class);
    }

    public static com.google.protobuf.Parser<Vtx> PARSER =
        new com.google.protobuf.AbstractParser<Vtx>() {
      public Vtx parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vtx(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Vtx> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LAT_FIELD_NUMBER = 1;
    private double lat_;
    /**
     * <code>required double Lat = 1;</code>
     */
    public boolean hasLat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double Lat = 1;</code>
     */
    public double getLat() {
      return lat_;
    }

    public static final int LNG_FIELD_NUMBER = 2;
    private double lng_;
    /**
     * <code>required double Lng = 2;</code>
     */
    public boolean hasLng() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double Lng = 2;</code>
     */
    public double getLng() {
      return lng_;
    }

    private void initFields() {
      lat_ = 0D;
      lng_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLng()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, lat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, lng_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, lat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, lng_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static VtxProto.Vtx parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VtxProto.Vtx parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VtxProto.Vtx parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VtxProto.Vtx parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VtxProto.Vtx parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static VtxProto.Vtx parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static VtxProto.Vtx parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static VtxProto.Vtx parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static VtxProto.Vtx parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static VtxProto.Vtx parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(VtxProto.Vtx prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Vtx}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Vtx)
        VtxProto.VtxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return VtxProto.internal_static_Vtx_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return VtxProto.internal_static_Vtx_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                VtxProto.Vtx.class, VtxProto.Vtx.Builder.class);
      }

      // Construct using VtxProto.Vtx.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        lat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        lng_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return VtxProto.internal_static_Vtx_descriptor;
      }

      public VtxProto.Vtx getDefaultInstanceForType() {
        return VtxProto.Vtx.getDefaultInstance();
      }

      public VtxProto.Vtx build() {
        VtxProto.Vtx result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public VtxProto.Vtx buildPartial() {
        VtxProto.Vtx result = new VtxProto.Vtx(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lat_ = lat_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lng_ = lng_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof VtxProto.Vtx) {
          return mergeFrom((VtxProto.Vtx)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(VtxProto.Vtx other) {
        if (other == VtxProto.Vtx.getDefaultInstance()) return this;
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasLng()) {
          setLng(other.getLng());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLat()) {
          
          return false;
        }
        return hasLng();
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        VtxProto.Vtx parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (VtxProto.Vtx) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double lat_ ;
      /**
       * <code>required double Lat = 1;</code>
       */
      public boolean hasLat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double Lat = 1;</code>
       */
      public double getLat() {
        return lat_;
      }
      /**
       * <code>required double Lat = 1;</code>
       */
      public Builder setLat(double value) {
        bitField0_ |= 0x00000001;
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double Lat = 1;</code>
       */
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lat_ = 0D;
        onChanged();
        return this;
      }

      private double lng_ ;
      /**
       * <code>required double Lng = 2;</code>
       */
      public boolean hasLng() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double Lng = 2;</code>
       */
      public double getLng() {
        return lng_;
      }
      /**
       * <code>required double Lng = 2;</code>
       */
      public Builder setLng(double value) {
        bitField0_ |= 0x00000002;
        lng_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double Lng = 2;</code>
       */
      public Builder clearLng() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lng_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Vtx)
    }

    static {
      defaultInstance = new Vtx(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Vtx)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vtx_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Vtx_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tVtx.proto\"\037\n\003Vtx\022\013\n\003Lat\030\001 \002(\001\022\013\n\003Lng\030\002" +
      " \002(\001B\nB\010VtxProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Vtx_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Vtx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Vtx_descriptor,
        new java.lang.String[] { "Lat", "Lng", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
